# Generated by Django 5.2.15 on 2026-06-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_price_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=120)),
                ("roll_number", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("college", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
