# Generated by Django 4.2.30 on 2026-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_aes_gcm_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaintextfile',
            name='receiver_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
