# Generated by Django 4.2.30 on 2026-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_plaintextfile_receiver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaintextfile',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
