databases:
  - name: anrkitdept-db
    databaseName: anrkitdept
    user: anrkitdept_user
    plan: free
    region: oregon

services:
  - type: web
    name: anrkitdept
    runtime: python
    pythonVersion: 3.10.11
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: free
    region: oregon
    apt:
      packages:
        - libpango-1.0-0
        - libpangocairo-1.0-0
        - libcairo2
        - libgdk-pixbuf2.0-0
        - libffi-dev
        - libxml2
        - libxslt1.1
        - shared-mime-info
        - libpangoft2-1.0-0
        - fonts-dejavu-core
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anrkitdept-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PHONEPE_ENVIRONMENT
        value: "sandbox"
      - key: PHONEPE_CLIENT_ID
        sync: false
      - key: PHONEPE_CLIENT_SECRET
        sync: false
      - key: PHONEPE_CLIENT_VERSION
        value: "1"
      - key: PHONEPE_CALLBACK_USERNAME
        sync: false
      - key: PHONEPE_CALLBACK_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: "engineeringcollege.onrender.com,anrkitdept.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://engineeringcollege.onrender.com,https://anrkitdept.onrender.com"
      - key: PYTHON_VERSION
        value: "3.10.11"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
