# Generated by manual edit
from django.db import migrations
from django.conf import settings
import os

def update_student_cloudinary_urls(apps, schema_editor):
    """
    Update student records with Cloudinary URLs for photos and certificates.
    On Render, media files are stored in Cloudinary. This migration populates
    the URL fields with Cloudinary URLs based on student HT numbers.
    """
    Student = apps.get_model('dashboard', 'Student')
    cloud_name = getattr(settings, 'CLOUDINARY_CLOUD_NAME', None)
    if not cloud_name:
        return

    # Build base Cloudinary URL templates (matches sync_student_assets_to_cloudinary command)
    photo_url_template = f'https://res.cloudinary.com/{cloud_name}/image/upload/student_photos/{{ht_no}}_photo.jpg'
    cert_url_template = f'https://res.cloudinary.com/{cloud_name}/raw/upload/student_certs/{{cert_type}}/{{ht_no}}_{{cert_type}}.pdf'

    updated = 0
    for student in Student.objects.all():
        changed = False

        # Update photo_url if photo exists but photo_url is empty or still points to local path
        if student.photo and (not student.photo_url or not student.photo_url.startswith('http')):
            student.photo_url = photo_url_template.format(ht_no=student.ht_no)
            changed = True

        # Update certificate URLs
        cert_fields = [
            ('cert_achieve', 'achievement'),
            ('cert_intern', 'internship'),
            ('cert_courses', 'courses'),
            ('cert_sdp', 'sdp'),
            ('cert_extra', 'extra'),
            ('cert_placement', 'placement'),
            ('cert_national', 'national'),
        ]

        for field_name, cert_type in cert_fields:
            file_field = getattr(student, field_name)
            url_field_name = f'{field_name}_url'
            current_url = getattr(student, url_field_name)
            if file_field and (not current_url or not current_url.startswith('http')):
                setattr(student, url_field_name, cert_url_template.format(
                    ht_no=student.ht_no, cert_type=cert_type
                ))
                changed = True

        if changed:
            student.save(update_fields=[
                'photo_url',
                'cert_achieve_url', 'cert_intern_url', 'cert_courses_url',
                'cert_sdp_url', 'cert_extra_url', 'cert_placement_url', 'cert_national_url'
            ])
            updated += 1

    return updated

class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0002_add_missing_phd_title'),
    ]

    operations = [
        migrations.RunPython(update_student_cloudinary_urls, reverse_code=migrations.RunPython.noop),
    ]
