# Generated by Django 4.2.7 on 2026-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_sync_student_cloudinary_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cert_achieve',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/achievement/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_courses',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/courses/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_extra',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/extra/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_intern',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/internship/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_national',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/national/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_placement',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/placement/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_sdp',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/sdp/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_pdfs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='student_photos/'),
        ),
    ]
