# Generated by data migration to fix incorrect Cloudinary PDF URLs
from django.db import migrations

def fix_student_pdf_urls(apps, schema_editor):
    """
    Regenerate student PDFs for records that have an incorrect Cloudinary URL
    using '/image/upload/' (which is for images, not PDFs). PDFs must use
    '/raw/upload/' to be served correctly.
    """
    from django.conf import settings
    if not getattr(settings, 'CLOUDINARY_CONFIGURED', False):
        print("Cloudinary not configured — skipping student PDF URL fix.")
        return

    Student = apps.get_model('dashboard', 'Student')
    # Import here to avoid circular imports during migration
    from dashboard.views import generate_student_pdf

    # Find students whose pdf_url uses the 'image' resource type
    bad_students = Student.objects.filter(
        pdf_url__icontains='/image/upload/'
    ).order_by('id')

    total = bad_students.count()
    if total == 0:
        print("No students with incorrect PDF URLs found.")
        return

    print(f"Found {total} student(s) with incorrect PDF URLs. Regenerating...")
    updated = 0
    for student in bad_students:
        try:
            print(f"  Regenerating PDF for {student.student_name} (HT: {student.ht_no})...")
            generate_student_pdf(student)
            updated += 1
            print(f"  ✓ Done.")
        except Exception as e:
            print(f"  ✗ Failed for {student.ht_no}: {e}")

    print(f"Updated {updated}/{total} student PDF URLs.")

class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0014_alter_student_cert_achieve_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_student_pdf_urls, reverse_code=migrations.RunPython.noop),
    ]
