# Generated by Django 4.2.7 on 2026-06-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_faculty_is_ratified_faculty_membership_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='membership_proof',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/membership_proofs/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='membership_proof_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
