# Generated by Django 4.2.7 on 2026-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_faculty_membership_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
