# Generated by Django 4.2.7 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_faculty_college_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='tstsabas_entries',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Repeatable TSTSABAS professional information entries',
            ),
        ),
    ]
