# Generated by Django 4.2.7 on 2026-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_faculty_tstsabas_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDownloadPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_id', models.CharField(max_length=64, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('amount_paise', models.PositiveIntegerField(default=100000)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('phonepe_order_id', models.CharField(blank=True, max_length=128)),
                ('payment_url', models.URLField(blank=True, max_length=1000)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
