# Generated by Django 4.2.30 on 2026-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_kavachsecurefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kavachsecurefile',
            name='receiver_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='sender_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
