# Generated by Django 4.2.7 on 2026-01-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('aadhar', models.CharField(max_length=20)),
                ('apaar_id', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('parent_phone', models.CharField(max_length=10)),
                ('student_phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('task_registered', models.CharField(blank=True, max_length=3, null=True)),
                ('task_username', models.CharField(blank=True, max_length=50)),
                ('csi_registered', models.CharField(blank=True, max_length=3, null=True)),
                ('csi_membership_id', models.CharField(blank=True, max_length=50)),
                ('admission_type', models.CharField(blank=True, max_length=20, null=True)),
                ('other_admission_details', models.CharField(blank=True, max_length=100)),
                ('eamcet_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('sem', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='students/photos/')),
                ('ssc_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inter_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rtrp_title', models.CharField(blank=True, max_length=200)),
                ('intern_title', models.CharField(blank=True, max_length=200)),
                ('final_project_title', models.CharField(blank=True, max_length=200)),
                ('cert_achieve', models.FileField(blank=True, upload_to='students/certificates/')),
                ('cert_intern', models.FileField(blank=True, upload_to='students/certificates/')),
                ('cert_courses', models.FileField(blank=True, upload_to='students/certificates/')),
                ('cert_sdp', models.FileField(blank=True, upload_to='students/certificates/')),
                ('cert_extra', models.FileField(blank=True, upload_to='students/certificates/')),
                ('cert_placement', models.FileField(blank=True, upload_to='students/certificates/')),
                ('cert_national', models.FileField(blank=True, upload_to='students/certificates/')),
                ('other_training', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.department')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.faculty')),
            ],
        ),
    ]
