# Generated by Django 4.2.7 on 2026-02-14 16:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(blank=True, default='Indian', max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar', models.CharField(max_length=20)),
                ('apaar_id', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
                ('parent_phone', models.CharField(max_length=15)),
                ('student_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('task_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('task_username', models.CharField(blank=True, max_length=100, null=True)),
                ('csi_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('csi_membership_id', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_type', models.CharField(max_length=100)),
                ('other_admission_details', models.CharField(blank=True, max_length=200, null=True)),
                ('eamcet_rank', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('ssc_marks', models.FloatField(blank=True, null=True)),
                ('inter_marks', models.FloatField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('rtrp_project_title', models.CharField(blank=True, max_length=300, null=True)),
                ('intern_title', models.CharField(blank=True, max_length=300, null=True)),
                ('final_project_title', models.CharField(blank=True, max_length=300, null=True)),
                ('other_training', models.TextField(blank=True, null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('cert_achieve', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('cert_intern', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('cert_courses', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('cert_sdp', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('cert_extra', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('cert_placement', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('cert_national', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('pdf_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
