# Generated by Django 4.2.7 on 2026-01-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('certificate', models.FileField(blank=True, upload_to='faculty/research/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_activities', to='dashboard.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_sem', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=500)),
                ('ht_no', models.CharField(blank=True, max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('marks', models.CharField(blank=True, max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dashboard.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('ssc_year', models.IntegerField(blank=True, null=True)),
                ('ssc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ssc_school', models.CharField(blank=True, max_length=500)),
                ('inter_year', models.IntegerField(blank=True, null=True)),
                ('inter_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inter_college', models.CharField(blank=True, max_length=500)),
                ('btech_year', models.IntegerField(blank=True, null=True)),
                ('btech_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('btech_college', models.CharField(blank=True, max_length=500)),
                ('btech_specialization', models.CharField(blank=True, max_length=200)),
                ('edu_certificates', models.FileField(blank=True, upload_to='faculty/edu_certificates/')),
                ('subjects_dealt', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('memberships', models.JSONField(blank=True, default=list)),
                ('research', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dashboard.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('certificate', models.FileField(blank=True, upload_to='faculty/memberships/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dashboard.faculty')),
            ],
        ),
    ]
