# Generated by Django 4.2.7 on 2026-03-26 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_faculty_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btechproject',
            options={'ordering': ['-batch']},
        ),
        migrations.AlterModelOptions(
            name='cloudinaryupload',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['staff_name'], 'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterModelOptions(
            name='researchpublication',
            options={'ordering': ['-publication_year']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='btechproject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='aadhar_document',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='apaar_document',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='pan_document',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='scm_document',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fdp',
            name='certificate_upload',
        ),
        migrations.RemoveField(
            model_name='fdp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fdp',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='faculty_profile',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='upload_pdf',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='award_description',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='award_level',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='best_paper_award',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='chapter_number',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='co_investigators',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='commercialized',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='conference_type',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='copyright_description',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='copyright_office',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='copyright_registration_date',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='copyright_registration_number',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='e_issn',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='fund_received',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='impact_factor',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='indexed_in',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='inventors',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='license_details',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='number_of_pages',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='open_access',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='patent_office',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='patent_status',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='patent_title',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='patent_type',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='presentation_type',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='principal_investigator',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='proceedings_title',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='publication_place',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='quartile',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='role',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='sanction_number',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='researchpublication',
            name='ugc_care_listed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='certificate',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='dashboard.subject'),
        ),
        migrations.AddField(
            model_name='fdp',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='fdp_certificates/'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='btechproject',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='btechproject',
            name='ht_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='btechproject',
            name='marks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudinaryupload',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.faculty'),
        ),
        migrations.AlterField(
            model_name='cloudinaryupload',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student'),
        ),
        migrations.AlterField(
            model_name='cloudinaryupload',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='aadhar_file',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/aadhar/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='apaar_file',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/apaar/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employee_code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='exp_anurag',
            field=models.CharField(blank=True, help_text='Experience at Anurag Engineering College', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='exp_other',
            field=models.CharField(blank=True, help_text='Experience at other institutions', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='inter_certificate',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/inter/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='inter_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='jntuh_biodata',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/biodata/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='nationality',
            field=models.CharField(default='Indian', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/pan/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='faculty_pdfs/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pg_certificate',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/pg/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pg_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pg_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pg_spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phd_certificate',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/phd/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phd_degree',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pursuing', 'Pursuing'), ('Not Started', 'Not Started'), ('', 'Not Specified')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phd_spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phd_university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='results',
            field=models.TextField(blank=True, help_text='Student results or academic performance', null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='scm',
            field=models.TextField(blank=True, help_text='Service Cum Merit details', null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='scm_file',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/scm/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ssc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/ssc/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ssc_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='staff_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subjects_dealt',
            field=models.TextField(blank=True, help_text='List of subjects handled, separated by commas', null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ug_certificate',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/ug/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ug_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ug_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ug_spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.faculty'),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='performed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='experience_at_anurag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='experience_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dashboard.faculty'),
        ),
        migrations.AlterField(
            model_name='fdp',
            name='fdp_type',
            field=models.CharField(choices=[('fdp', 'FDP'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('training', 'Training Program')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fdp',
            name='level',
            field=models.CharField(blank=True, choices=[('institute', 'Institute Level'), ('college', 'College Level'), ('university', 'University Level'), ('state', 'State Level'), ('national', 'National Level'), ('international', 'International Level')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fdp',
            name='mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fdp',
            name='organized_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fdp',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fdp',
            name='role',
            field=models.CharField(blank=True, choices=[('participant', 'Participant'), ('presenter', 'Presenter'), ('resource_person', 'Resource Person'), ('organizer', 'Organizer'), ('coordinator', 'Coordinator')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fdp',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='issn_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='marks_awarded',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='research_type',
            field=models.CharField(choices=[('journal', 'Journal Publication'), ('conference', 'Conference Paper'), ('book', 'Book/Chapter'), ('patent', 'Patent'), ('project', 'Research Project'), ('award', 'Award/Recognition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='award_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='awarding_body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='book_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='conference_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='conference_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='issn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='journal_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='project_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='research_proofs/'),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='research_type',
            field=models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book Chapter'), ('patent', 'Patent'), ('project', 'Research Project'), ('award', 'Award/Recognition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='sanction_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchpublication',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('accepted', 'Accepted'), ('under_review', 'Under Review'), ('submitted', 'Submitted'), ('in_progress', 'In Progress')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_achieve',
            field=models.FileField(blank=True, null=True, upload_to='student_certs/achievement/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_courses',
            field=models.FileField(blank=True, null=True, upload_to='student_certs/courses/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_extra',
            field=models.FileField(blank=True, null=True, upload_to='student_certs/extra/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_intern',
            field=models.FileField(blank=True, null=True, upload_to='student_certs/internship/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_national',
            field=models.FileField(blank=True, null=True, upload_to='student_certs/national/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_placement',
            field=models.FileField(blank=True, null=True, upload_to='student_certs/placement/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cert_sdp',
            field=models.FileField(blank=True, null=True, upload_to='student_certs/sdp/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='csi_registered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='eamcet_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ht_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='inter_marks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='student_pdfs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_marks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='task_registered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
