# Generated by Django 4.2.7 on 2026-01-26 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_facultyresearch_facultyproject_facultyprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('SSC', 'Secondary School Certificate (SSC)'), ('INTERMEDIATE', 'Intermediate'), ('BTECH', 'Bachelor of Technology (B.Tech)'), ('MTECH', 'Master of Technology (M.Tech)'), ('PHD', 'Ph.D'), ('OTHERS', 'Other Qualifications')], max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('institution', models.CharField(blank=True, max_length=500)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('certificate', models.FileField(blank=True, upload_to='faculty/edu_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SCM', 'SCM'), ('FDP', 'FDP'), ('MEMBERSHIP', 'Membership'), ('ACHIEVEMENT', 'Achievement'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('certificate', models.FileField(blank=True, upload_to='faculty/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_sem', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=20)),
                ('hall_ticket', models.CharField(blank=True, max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('marks', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('CONFERENCE', 'Conference Paper'), ('JOURNAL', 'Journal Article'), ('BOOK_CHAPTER', 'Book Chapter'), ('PATENT', 'Patent'), ('BOOK', 'Book'), ('WORKSHOP', 'Workshop')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('journal_conference', models.CharField(blank=True, max_length=500)),
                ('volume_issue', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi_isbn', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('certificate', models.FileField(blank=True, upload_to='faculty/publications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_sem', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=500)),
                ('appeared', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDealt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facultyproject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultyresearch',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='btech_college',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='btech_percentage',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='btech_specialization',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='btech_year',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='edu_certificates',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='inter_college',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='inter_percentage',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='inter_year',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='ssc_percentage',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='ssc_school',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='ssc_year',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='about',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='bank_address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='fdp',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='publications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='scm',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dashboard.faculty'),
        ),
        migrations.DeleteModel(
            name='FacultyMembership',
        ),
        migrations.DeleteModel(
            name='FacultyProject',
        ),
        migrations.DeleteModel(
            name='FacultyResearch',
        ),
        migrations.AddField(
            model_name='subjectdealt',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='dashboard.facultyprofile'),
        ),
        migrations.AddField(
            model_name='result',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_data', to='dashboard.facultyprofile'),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_data', to='dashboard.facultyprofile'),
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_students', to='dashboard.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultydocument',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.facultyprofile'),
        ),
        migrations.AddField(
            model_name='educationalqualification',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='dashboard.facultyprofile'),
        ),
    ]
