# Generated by Django 4.2.7 on 2026-04-15 15:43

from django.db import migrations, models, connection


def _create_tables_if_not_exist(schema_editor):
    db_backend = connection.vendor
    if db_backend == 'postgresql':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS dashboard_researchpublication (
                id BIGSERIAL PRIMARY KEY,
                research_type VARCHAR(20),
                title VARCHAR(500) NOT NULL,
                authors TEXT,
                department VARCHAR(100),
                publication_year INTEGER,
                academic_year VARCHAR(20),
                status VARCHAR(20),
                doi VARCHAR(100),
                url VARCHAR(200),
                abstract TEXT,
                keywords VARCHAR(500),
                journal_name VARCHAR(300),
                issn VARCHAR(20),
                volume VARCHAR(50),
                issue VARCHAR(50),
                page_numbers VARCHAR(50),
                conference_name VARCHAR(300),
                conference_location VARCHAR(200),
                conference_dates VARCHAR(100),
                book_title VARCHAR(300),
                isbn VARCHAR(20),
                edition VARCHAR(50),
                patent_number VARCHAR(100),
                filing_date DATE,
                grant_date DATE,
                project_title VARCHAR(300),
                funding_agency VARCHAR(200),
                sanction_amount VARCHAR(100),
                award_title VARCHAR(300),
                awarding_body VARCHAR(200),
                award_date DATE,
                publisher_name VARCHAR(200),
                proof_document VARCHAR(100),
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                faculty_id BIGINT REFERENCES dashboard_faculty(id) ON DELETE CASCADE
            );
        """)
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS dashboard_fdp (
                id BIGSERIAL PRIMARY KEY,
                fdp_type VARCHAR(20),
                title VARCHAR(300) NOT NULL,
                from_date DATE NOT NULL,
                to_date DATE NOT NULL,
                academic_year VARCHAR(20),
                organized_by VARCHAR(200),
                place VARCHAR(200),
                mode VARCHAR(20),
                level VARCHAR(20),
                role VARCHAR(20),
                sponsored_by VARCHAR(200),
                remarks TEXT,
                certificate VARCHAR(100),
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                faculty_id BIGINT REFERENCES dashboard_faculty(id) ON DELETE CASCADE
            );
        """)
    elif db_backend == 'sqlite':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS dashboard_researchpublication (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                research_type VARCHAR(20),
                title VARCHAR(500) NOT NULL,
                authors TEXT,
                department VARCHAR(100),
                publication_year INTEGER,
                academic_year VARCHAR(20),
                status VARCHAR(20),
                doi VARCHAR(100),
                url VARCHAR(200),
                abstract TEXT,
                keywords VARCHAR(500),
                journal_name VARCHAR(300),
                issn VARCHAR(20),
                volume VARCHAR(50),
                issue VARCHAR(50),
                page_numbers VARCHAR(50),
                conference_name VARCHAR(300),
                conference_location VARCHAR(200),
                conference_dates VARCHAR(100),
                book_title VARCHAR(300),
                isbn VARCHAR(20),
                edition VARCHAR(50),
                patent_number VARCHAR(100),
                filing_date DATE,
                grant_date DATE,
                project_title VARCHAR(300),
                funding_agency VARCHAR(200),
                sanction_amount VARCHAR(100),
                award_title VARCHAR(300),
                awarding_body VARCHAR(200),
                award_date DATE,
                publisher_name VARCHAR(200),
                proof_document VARCHAR(100),
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                faculty_id INTEGER REFERENCES dashboard_faculty(id) ON DELETE CASCADE
            );
        """)
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS dashboard_fdp (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                fdp_type VARCHAR(20),
                title VARCHAR(300) NOT NULL,
                from_date DATE NOT NULL,
                to_date DATE NOT NULL,
                academic_year VARCHAR(20),
                organized_by VARCHAR(200),
                place VARCHAR(200),
                mode VARCHAR(20),
                level VARCHAR(20),
                role VARCHAR(20),
                sponsored_by VARCHAR(200),
                remarks TEXT,
                certificate VARCHAR(100),
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                faculty_id INTEGER REFERENCES dashboard_faculty(id) ON DELETE CASCADE
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_cert_url_fields'),
    ]

    operations = [
        # Ensure ALL required tables exist before adding fields (for deployment fixes)
        migrations.RunPython(
            lambda apps, schema_editor: _create_tables_if_not_exist(schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='fdp',
            name='certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='proof_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
