# Generated by Django 4.2.7 on 2026-04-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_cert_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdp',
            name='certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='proof_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
