# Generated by Django 4.2.7 on 2025-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
