# Generated by Django 4.2.7 on 2026-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_btechproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='employee_code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='staff_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
