# Generated by Django 4.2.7 on 2026-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phd_degree',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pursuing', 'Pursuing'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50, null=True),
        ),
    ]
