# Generated by Django 4.2.7 on 2026-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_faculty_employee_code_alter_faculty_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='aadhar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='apaar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='inter_certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='jntuh_biodata_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pan_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pg_certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phd_certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='scm_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='ssc_certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='ug_certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
