# Generated by Django 4.2.7 on 2026-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_faculty_aadhar_url_faculty_apaar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='classes_taken',
            field=models.IntegerField(blank=True, help_text='Number of classes taken by the faculty', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='experience_certificates',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/experience_certs/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='experience_certificates_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/other_docs/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='other_documents_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
