# Generated by Django 4.2.7 on 2026-01-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_faculty_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cloudinary_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='cloudinary_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
