# Generated by Django 4.2.7 on 2026-04-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_updated_at_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
