# Generated by Django 4.2.7 on 2026-01-08 20:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_studentregistration_apaar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_photos'),
        ),
    ]
