# Generated by Django 4.2.7 on 2026-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_faculty_cloudinary_pdf_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('apaar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('student_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('task_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('task_username', models.CharField(blank=True, max_length=100, null=True)),
                ('csi_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('csi_membership_id', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_type', models.CharField(blank=True, max_length=50, null=True)),
                ('other_admission_details', models.CharField(blank=True, max_length=200, null=True)),
                ('eamcet_rank', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('ssc_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inter_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rtrp_title', models.CharField(blank=True, max_length=300, null=True)),
                ('intern_title', models.CharField(blank=True, max_length=300, null=True)),
                ('final_project_title', models.CharField(blank=True, max_length=300, null=True)),
                ('other_training', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
