# Generated by Django 4.2.7 on 2026-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_faculty_classes_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='experience_certificates_academic_year',
            field=models.CharField(blank=True, help_text='Academic year for experience certificates', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='fdp_certificate',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/fdp_certificates/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='fdp_certificate_academic_year',
            field=models.CharField(blank=True, help_text='Academic year for FDP certificate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='fdp_certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='other_documents_academic_year',
            field=models.CharField(blank=True, help_text='Academic year for other documents', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_proof',
            field=models.FileField(blank=True, null=True, upload_to='faculty_docs/research_proofs/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_proof_academic_year',
            field=models.CharField(blank=True, help_text='Academic year for research proof document', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_proof_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fdp',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2023-24)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2023-24)', max_length=20, null=True),
        ),
    ]
