# Generated by Django 4.2.7 on 2026-04-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phd_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
