# Generated by Django 4.2.7 on 2026-02-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
