# Generated by Django 4.2.7 on 2026-01-08 22:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_studentregistration_pdf_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentregistration',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_achieve',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_courses',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_extra',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_intern',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_national',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_placement',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_sdp',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='final_project_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='intern_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='other_admission_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='other_training',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='religion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='rtrp_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
