# Generated by Django 4.2.7 on 2026-02-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='achievement_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='internship_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='national_exam_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='pdf_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='pdf_generation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_offer',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='sdp_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
