# Generated by Django 4.2.7 on 2026-01-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_studentregistration_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_achieve',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_courses',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_extra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_intern',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_national',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_placement',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='cert_sdp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
