# Generated by Django 4.2.7 on 2026-02-08 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_student_achievement_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['employee_code']},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='inter_college',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='inter_percent',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='inter_year',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pg_college',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pg_percentage',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pg_spec',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pg_year',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phd_degree',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phd_spec',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phd_university',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phd_year',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ssc_percent',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ssc_school',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ssc_year',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='state',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='sub_caste',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subjects_dealt',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ug_college',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ug_percentage',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ug_spec',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ug_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='csi_membership_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='csi_registered',
        ),
        migrations.RemoveField(
            model_name='student',
            name='eamcet_rank',
        ),
        migrations.RemoveField(
            model_name='student',
            name='final_project_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='intern_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_admission_details',
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_training',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rtrp_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='task_registered',
        ),
        migrations.RemoveField(
            model_name='student',
            name='task_username',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudinaryupload',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudinaryupload',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(default='General Certificate', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cloudinaryupload',
            name='resource_type',
            field=models.CharField(default='raw', max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudinaryupload',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cloudinaryupload',
            name='upload_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='action',
            field=models.CharField(default='ACTION', max_length=50),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultylog',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
