# Generated by Django 4.2.7 on 2026-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_facultyprofile_faculty_results_researchproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pdf_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
