# Generated by Django 4.2.7 on 2026-02-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_faculty_options_remove_faculty_caste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.AddField(
            model_name='faculty',
            name='phd_degree',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pursuing', 'Pursuing'), ('Not Started', 'Not Started')], default='Not Started', max_length=20),
        ),
    ]
