# Generated by Django 4.2.7 on 2026-01-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_studentregistration_eamcet_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='task_registered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='task_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
