# Generated by Django 4.2.7 on 2026-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_cloudinaryupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
