# Generated by Django 4.2.7 on 2026-02-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='achievement_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='csi_membership_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='csi_registered',
        ),
        migrations.RemoveField(
            model_name='student',
            name='extra_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='final_project_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='intern_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internship_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_exam_certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_training',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='placement_offer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rtrp_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sdp_certificate',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='dashboard.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
    ]
