# Generated by Django 4.2.7 on 2026-01-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_csi_id_studentregistration_csi_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='csi_membership_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='csi_registered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='task_registered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='task_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
