# Generated by Django 4.2.7 on 2026-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_fix_student_pdf_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='btech_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_achieve_additional',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/achievement/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_achieve_additional_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_courses_additional',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/courses/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_courses_additional_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_extra_additional',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/extra/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_extra_additional_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_intern_additional',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/internship/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_intern_additional_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_national_additional',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/national/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_national_additional_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_placement_additional',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/placement/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_placement_additional_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_sdp_additional',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='student_certs/sdp/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cert_sdp_additional_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='inter_college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='inter_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ug_college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
