# Generated by Django 4.2.7 on 2026-06-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_student_btech_year_student_cert_achieve_additional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(blank=True, choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book Chapter'), ('patent', 'Patent'), ('project', 'Research Project'), ('award', 'Award/Recognition')], max_length=20, null=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=300, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=300, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('published', 'Published'), ('accepted', 'Accepted'), ('under_review', 'Under Review'), ('submitted', 'Submitted'), ('in_progress', 'In Progress')], max_length=20, null=True)),
                ('proof_document', models.FileField(blank=True, max_length=500, null=True, upload_to='student_research_proofs/')),
                ('proof_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_publications', to='dashboard.student')),
            ],
            options={
                'ordering': ['-publication_year', '-id'],
            },
        ),
    ]
