# Generated by Django 4.2.7 on 2026-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_cloudinaryupload_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phd_degree',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pursuing', 'Pursuing'), ('Not Started', 'Not Started'), ('None', 'None')], default='Not Started', max_length=20),
        ),
    ]
