# Generated by Django 4.2.7 on 2026-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_studentresearchpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_ratified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='membership_academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='membership_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='membership_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
