# Generated by Django 4.2.7 on 2026-02-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_faculty_phd_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rttp_title',
            new_name='rtrp_project_title',
        ),
    ]
