# Generated by Django 4.2.7 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='college_experiences',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='College-wise employment history with address and date range',
            ),
        ),
    ]
