# Generated by Django 4.2.30 on 2026-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_kavachsecurefile_receiver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kavachsecurefile',
            name='digital_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='file_sha256_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='signature_algorithm',
            field=models.CharField(default='Ed25519-SHA256', max_length=40),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='uploader_public_key',
            field=models.TextField(blank=True),
        ),
    ]
