# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_kavachsecurefile_digital_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kavachsecurefile',
            name='aes_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='encrypted_aes_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='receiver_public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='kavachsecurefile',
            name='is_revoked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
