# Generated by Codex on 2026-06-14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_index=True, max_length=150)),
                ('activity_type', models.CharField(db_index=True, max_length=80)),
                ('file', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('event_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed')], db_index=True, default='open', max_length=20)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
