# Generated by Django 4.2.30 on 2026-07-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_suspiciousactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('9:00-10:00', '9:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-1:00', '12:00 PM - 1:00 PM'), ('2:00-3:00', '2:00 PM - 3:00 PM'), ('3:00-4:00', '3:00 PM - 4:00 PM'), ('4:00-5:00', '4:00 PM - 5:00 PM')], max_length=20)),
                ('period_order', models.IntegerField()),
            ],
            options={
                'ordering': ['period_order'],
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('2-1', '2-1'), ('3-1', '3-1'), ('4-1', '4-1')], max_length=10)),
                ('year', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['semester', 'year'],
                'unique_together': {('semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('lab_code', models.CharField(max_length=50)),
                ('lab_name', models.CharField(max_length=200)),
                ('lab_room', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.CharField(blank=True, max_length=10, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_schedules', to='dashboard.faculty')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_schedules', to='dashboard.period')),
                ('students', models.ManyToManyField(blank=True, related_name='lab_schedules', to='dashboard.student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_schedules', to='dashboard.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'period'],
                'unique_together': {('timetable', 'day_of_week', 'period', 'lab_room')},
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
                ('time_type', models.CharField(choices=[('CLASS', 'Class'), ('LAB', 'Lab')], default='CLASS', max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('lab_room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.CharField(blank=True, max_length=10, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules', to='dashboard.faculty')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='dashboard.period')),
                ('students', models.ManyToManyField(blank=True, related_name='class_schedules', to='dashboard.student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='dashboard.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'period'],
                'unique_together': {('timetable', 'day_of_week', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('E', 'Excused')], max_length=1)),
                ('class_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.classschedule')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.student')),
            ],
            options={
                'ordering': ['-date', 'day_of_week', 'period'],
                'unique_together': {('student', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='LabEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('lab_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dashboard.labschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_enrollments', to='dashboard.student')),
            ],
            options={
                'ordering': ['lab_schedule', 'student__student_name'],
                'unique_together': {('lab_schedule', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FacultySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
                ('time_type', models.CharField(choices=[('CLASS', 'Class'), ('LAB', 'Lab')], default='CLASS', max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_schedules', to='dashboard.faculty')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_schedules', to='dashboard.period')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_schedules', to='dashboard.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'period'],
                'unique_together': {('timetable', 'day_of_week', 'period', 'faculty')},
            },
        ),
    ]
