# Generated by Django 4.2.30 on 2026-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_moocspayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoocsExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('set_number', models.PositiveIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('incorrect', models.PositiveIntegerField(default=0)),
                ('unattempted', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('total_questions', models.PositiveIntegerField(default=100)),
                ('max_marks', models.PositiveIntegerField(default=200)),
                ('subject_scores', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MOOCS Exam Result',
                'verbose_name_plural': 'MOOCS Exam Results',
                'ordering': ['-completed_at'],
                'unique_together': {('email', 'set_number')},
            },
        ),
    ]
