# Generated by Django 4.2.7 on 2025-11-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science & Engineering'), ('CSE_AIML', 'CSE (AI & ML)'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('hod_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('1-1', '1st Year 1st Semester'), ('1-2', '1st Year 2nd Semester'), ('2-1', '2nd Year 1st Semester'), ('2-2', '2nd Year 2nd Semester'), ('3-1', '3rd Year 1st Semester'), ('3-2', '3rd Year 2nd Semester'), ('4-1', '4th Year 1st Semester'), ('4-2', '4th Year 2nd Semester')], max_length=5)),
                ('credits', models.IntegerField(default=3)),
                ('course_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Laboratory'), ('WORKSHOP', 'Workshop'), ('PROJECT', 'Project'), ('SEMINAR', 'Seminar'), ('ELECTIVE', 'Elective')], default='THEORY', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='dashboard.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['department', 'semester', 'code'],
            },
        ),
    ]
