# Generated by Django 4.2.7 on 2025-11-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('PROF', 'Professor'), ('ASSO_PROF', 'Associate Professor'), ('ASST_PROF', 'Assistant Professor'), ('LECTURER', 'Lecturer'), ('HOD', 'Head of Department')], max_length=20)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.IntegerField(help_text='Experience in years')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='dashboard.department')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty',
                'ordering': ['department', 'designation', 'name'],
            },
        ),
    ]
