# Generated by Django 4.2.7 on 2026-01-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_syllabus_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('aadhar', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('parent_phone', models.CharField(max_length=15)),
                ('student_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('admission_type', models.CharField(max_length=50)),
                ('other_admission_details', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('ssc_marks', models.FloatField(blank=True, null=True)),
                ('inter_marks', models.FloatField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('rtrp_title', models.CharField(blank=True, max_length=200)),
                ('intern_title', models.CharField(blank=True, max_length=200)),
                ('final_project_title', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('cert_achieve', models.FileField(blank=True, null=True, upload_to='certificates/achievements/')),
                ('cert_intern', models.FileField(blank=True, null=True, upload_to='certificates/internships/')),
                ('cert_courses', models.FileField(blank=True, null=True, upload_to='certificates/courses/')),
                ('cert_sdp', models.FileField(blank=True, null=True, upload_to='certificates/sdp/')),
                ('cert_extra', models.FileField(blank=True, null=True, upload_to='certificates/extracurricular/')),
                ('cert_placement', models.FileField(blank=True, null=True, upload_to='certificates/placements/')),
                ('cert_national', models.FileField(blank=True, null=True, upload_to='certificates/national_exams/')),
                ('other_training', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
