# Generated by Django 4.2.7 on 2026-01-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='student_pdfs/'),
        ),
    ]
