# Generated by Django 4.2.7 on 2026-01-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_studentregistration_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
