# Generated by Django 4.2.7 on 2026-01-09 00:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_studentregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='final_project_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='intern_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_photo'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='rtrp_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
