# Generated by Django 4.2.7 on 2026-01-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_studentregistration_cert_achieve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='eamcet_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
