# Generated by Django 4.2.7 on 2026-01-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_studentregistration_task_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='csi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='csi_registered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
