# Generated by Django 4.2.7 on 2026-01-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_studentregistration_csi_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='csi_id',
            new_name='csi_membership_id',
        ),
    ]
