# Generated by Django 4.2.7 on 2026-01-17 12:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_studentregistration_csi_membership_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('jntuh_id', models.CharField(blank=True, max_length=50, null=True)),
                ('aicte_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=50, null=True)),
                ('apaar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_caste', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ssc_school', models.CharField(blank=True, max_length=200, null=True)),
                ('ssc_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ssc_percent', models.FloatField(blank=True, null=True)),
                ('inter_college', models.CharField(blank=True, max_length=200, null=True)),
                ('inter_year', models.CharField(blank=True, max_length=10, null=True)),
                ('inter_percent', models.FloatField(blank=True, null=True)),
                ('ug_college', models.CharField(blank=True, max_length=200, null=True)),
                ('ug_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ug_percentage', models.FloatField(blank=True, null=True)),
                ('ug_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_college', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_year', models.CharField(blank=True, max_length=10, null=True)),
                ('pg_percentage', models.FloatField(blank=True, null=True)),
                ('pg_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('phd_university', models.CharField(blank=True, max_length=200, null=True)),
                ('phd_year', models.CharField(blank=True, max_length=10, null=True)),
                ('phd_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('phd_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_anurag', models.CharField(blank=True, max_length=50, null=True)),
                ('exp_other', models.CharField(blank=True, max_length=50, null=True)),
                ('subjects_dealt', models.TextField(blank=True, help_text='Store subjects as comma-separated values', null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='faculty_photo')),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('pdf_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_yourself', models.TextField(blank=True, null=True)),
                ('faculty_achievements', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
