# Generated by Django 4.2.7 on 2026-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_facultyregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyregistration',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
