# Generated by Django 4.2.7 on 2026-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_facultyregistration_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyregistration',
            name='admission_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='eamcet_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='final_project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='inter_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='intern_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='other_admission_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='other_training',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='rtrp_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='ssc_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyregistration',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
