# Generated by Django 4.2.30 on 2026-08-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etors', '0003_seed_demo_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('cab_type', models.CharField(choices=[('MINI', 'Mini'), ('SEDAN', 'Sedan'), ('SUV', 'SUV')], max_length=8)),
                ('drop_address', models.CharField(max_length=240)),
                ('train_arrival_at', models.DateTimeField()),
                ('cab_arrival_at', models.DateTimeField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Arrived at station'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cab_booking', to='etors.booking')),
                ('pickup_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cab_pickups', to='etors.station')),
            ],
            options={
                'ordering': ('cab_arrival_at',),
            },
        ),
    ]
