# Generated by Django 4.2.30 on 2026-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='key_source',
            field=models.CharField(choices=[('password', 'Password Registration'), ('gmail', 'Gmail Sign In')], default='password', max_length=20),
        ),
    ]
